/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectApp;
import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        project.setName("Projeto Teste");
        project.setDescription("description");
        projectController.save(project);
        
        Task task = new Task();
        task.setIdProject(2);
        task.setName("TesteMain");
        task.setDescription("Ola");
        TaskController taskcontroller = new TaskController();
        taskcontroller.save(task);
        
     /*   project.setName("Novo nome do projeto");
        projectController.update(project);
        
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
*/
        
    }
}
